title: Jeremiah Hauth
description: >
  Jeremiah Hauth is a PhD student in Mechanical Engineering,
  University of Michigan, Ann Arbor.
copyright: Jeremiah Hauth
sass:
  sass_dir: assets/sass
url: ''
disqus_shortname:
facebook_username:
twitter_username: "jeremiahhauth"
linkedin_username:
instagram_username:
pinterest_username:
flickr_username:
github_username:  "jeremiahhauth"
scholar_username:
# feed_icon: rss
email: "hauthj@umich.edu"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
